### PR TITLE
Upgrade to LLVM 6.0

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks for doing all of these @inducer.

Would you have time to update `openmp` as well? If not, that's ok. Just thought I would ask. :)

**Comment by inducer** [comment]
I can do the version bump, but if it doesn't build for some reason, I'll have to punt.

**Comment by jakirkham** [comment]
Sure, that seems perfectly reasonable. Thanks. :)

**Comment by inducer** [comment]
@conda-forge-admin please rerender

**Comment by inducer** [comment]
The build fails with:

```
-- The CXX compiler identification is Clang 6.0.0
CMake Error at C:/bld/libcxx_1520729482931/_b_env/Library/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:771 (message):
  The Clang compiler tool
    "C:/bld/libcxx_1520729482931/_b_env/Library/bin/clang-cl.exe"
  targets the MSVC ABI but has a GNU-like command-line interface.  This is
  not supported.  Use 'clang-cl' instead, e.g.  by setting 'CXX=clang-cl' in
  the environment.
```

Which I read as "`clang-cl` won't work, use `clang-cl` instead". As a result,
I'm a little lost for what to do.

**Comment by isuruf** [comment]
See the commit message of https://github.com/Kitware/CMake/commit/f969f1a9ce1d0045b9d056fd08c4683c34c420fa.
I've sent a [PR](https://github.com/conda-forge/cmake-feedstock/pull/49) to upgrade cmake to 3.10.2 which includes that commit.

We can try cmake 3.9 which doesn't have this bug, but not sure whether what CMake will do siently.

**Comment by inducer** [comment]
Thanks for the tip. I've pushed a commit to prevent CMake 3.10 for now.

**Pull request merged**
