### PR TITLE
Link against the system's libunwind

### PR DESCRIPTION
**Pull request by jjerphan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

See: https://libcxx.llvm.org/ReleaseNotes/18.html#build-system-changes

### CODE REVIEW

**Comment by jjerphan** [comment]
@conda-forge-admin, please rerender

**Review by h-vetinari — CHANGES_REQUESTED** [review]
Thanks for finding the note about the unwinder changes. However, except the build script changes, this is wrong. I'll put up a PR that builds this for the dev label so we can test this against arcticdb

**Comment by jjerphan** [comment]
Let's iterate on `dev`, I let you steer the resolution. :wink:

**Comment by h-vetinari** [comment]
OK, so the linux failure in #167 means we might have a shot at removing `libunwind` again completely (I wasn't optimistic at first). Looks like this causes things to fail similarly as they did for libunwind - another question of spurious C++ flags breaking the C-only detection of pthreads.

**Comment by jjerphan** [comment]
To me, `libcxx-feedstock` repackaging `libunwind` seems curious to me as [`conda-forge/libunwind-feedstock`](https://github.com/conda-forge/libunwind-feedstock) is dedicated to its distibution (hence its deletion in 6777c33).

What was the reason for redistributing it?

**Comment by h-vetinari** [comment]
Please see #160 for that topic. But if the changes here work, we might not even need that.

**Comment by h-vetinari** [comment]
Ugh, https://github.com/conda-forge/arcticdb-feedstock/pull/251 still fails with the build from #168. It looked like a really good lead though... 😑

**Review by h-vetinari — APPROVED** [review]
Thanks, this is a clear improvement over the status quo, even though it doesn't fix osx yet.

**Pull request merged**
