### PR TITLE
libcxx 17.0.6

### LINKED ISSUE #110: upstream planning to move to 10.13 minimum MacOS SDK
See RFC: https://discourse.llvm.org/t/libc-bumping-minimal-deployment-target-for-building-the-dylib-static-library-on-macos/68912

It's unclear to me if this will be patchable (like the availability stuff), we'll see I guess.

### PR DESCRIPTION
**Pull request by h-vetinari**
Biggest change is that libcxx now hard-requires MacOS >=10.13, see #110 (particularly for the dylib, but a simple `# include` also fails if the SDK is too old). Since libcxx has such a central role in our MacOS stack (i.e. we always pull in newest libcxx), this will effectively mandate a move to 10.13 (as all packages having libcxx in host will generate a run-export on >=17.0.1, which effectively moves all compiled osx-packages to >=10.13), see https://github.com/conda-forge/conda-forge.github.io/issues/1844.

libcxx on linux now also requires glibc >=2.24, which we cannot yet satisfy because our sysroots are too old (and 2_28 hasn't materialized yet); this doesn't seem too big of an issue though, as libcxx-on-linux is not our default C++ stdlib and is used very little.

I've kept the compatibility with old clang by again rebasing the revert of https://github.com/llvm/llvm-project/commit/21f73d5826fb5024a27eaacafadfa316f58949c5; we're already far beyond the upstream support policy of "last 2 clang versions" by going back all the way to clang 11. This remains on a best-effort basis.

Closes #110

### CODE REVIEW

**Comment by h-vetinari** [comment]
The error here does not make sense to me:
```
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - __osx >=10.13
 - libcxx-testing 0.15.*
 - libcxx 17.0.1.* hdf9962f_0

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package libcxx-testing-0.15-h007348e_1 is excluded by strict repo priority
```
as the package in question is [definitely](https://anaconda.org/conda-forge/libcxx-testing/files) in the main channel.

**Comment by h-vetinari** [comment]
> The error here does not make sense to me: [...]

Even less so because the final environment with `libcxx-testing 0.15` only contains packages from conda-forge... Not sure where the solver gets lost without flexible channel priority 🤔

**Comment by h-vetinari** [comment]
In any case, this is ready for review @conda-forge/libcxx! 

Please note that since libcxx now only supports MacOS >=10.13 which - given the importance of libcxx in conda-forge - has pretty far-reaching implications (AFAIU). More context in the OP.

I [summarized](https://github.com/conda-forge/conda-forge.github.io/issues/1844#issuecomment-1735037095) my understanding of the situation in the issue about the conda-forge-wide move to 10.13 -- I'd be happy to be challenged or corrected on this. My preference would be to add a `macosx_deployment_target_{{ target_platform }}>=10.13` run-export to our compilers for osx-64, to avoid waiting for months until `{{ stdlib("c") }}` is rolled out & fully functional.

**Comment by h-vetinari** [comment]
Gentle ping @conda-forge/libcxx

**Comment by xhochy** [comment]
> libcxx on linux now also requires glibc >=2.24, which we cannot yet satisfy because our sysroots are too old (and 2_28 hasn't materialized yet); this doesn't seem too big of an issue though, as libcxx-on-linux is not our default C++ stdlib and is used very little.

Shouldn't this be visible as failed build here with the old sysroot?

**Comment by h-vetinari** [comment]
> Shouldn't this be visible as failed build here with the old sysroot?

So far, the requirement seems to be a question of policy only (or at least not build-relevant yet). But we don't really use libcxx on Linux anywhere that I'm aware of, so it's hard to know if some codepath for glibc<2.24 is not being tested anymore or already broken at runtime.

**Comment by xhochy** [comment]
Then let's merge and see if anyone complains. At least that seems like the only way to find a failing test.

**Comment by h-vetinari** [comment]
I had asked @isuruf privately about how to proceed, and according to him it was decided at a core meeting that this'll have to wait until `{{ stdlib("c") }}` is [implemented](https://github.com/conda/conda-build/pull/4999) in conda-build and rolled out across conda-forge (at the same meeting where I had put it on the agenda _not_ to do this, though I couldn't argue my case because I ended up missing that call; @beckermr [said](https://matrix.to/#/!roreiEhVGuwollMYAc:gitter.im/$gO152A85oKJKGTdaAWUGkSJiGFq4p-D3hdleRDgD0is) the topic wasn't discussed, so there's some information asymmetry here; such a decision is also not mentioned in the [minutes](https://github.com/conda-forge/conda-forge.github.io/blob/main/src/orga/minutes/2023-09-06.md)).

To merge this PR, we need either `{{ stdlib("c") }}` on ~all compiled feedstocks, or a strong run-export of `__osx>=10.13` on all current osx compilers (clang 15/16 at least). Isuru is strongly opposed to the latter for reasons I don't know and have been unable to clarify.

So unless we revisit that decision, this PR (and by extension, clang 17 in conda-forge) is going to have to wait for a couple months.

**Comment by h-vetinari** [comment]
This is running into https://github.com/conda-forge/python-symengine-feedstock/issues/50

**Comment by h-vetinari** [comment]
With the imminent merge of https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5829, this is not a draft anymore - please feel free to review @conda-forge/libcxx :)

I feel this PR is in a good shape though, so planning to merge after Monday EOD AoE unless there are comments.

**Pull request merged**
