### PR TITLE
Remove-clang-dependency

### PR DESCRIPTION
**Pull request by SylvainCorlay**
This removes the runtime dependency of libcxx on clang, which prevents llvm and clang to depend on it and be built with `-D LLVM_ENABLE_LIBCXX`.

I am not quite sure why this was there in the first place. Actually also for the build-time dependency.

### CODE REVIEW

**Comment by jakirkham** [comment]
Build number bump?

**Comment by inducer** [comment]
LGTM, except for build number bump.

**Comment by jakirkham** [comment]
Any news on this @SylvainCorlay?

**Comment by jakirkham** [comment]
Thinking about this more, we shouldn't drop this entirely, but instead make it `run_constrained`. This will make it an optional dependency (so not always installed), but ensure the version matches if it is installed. Here's an [example]( https://github.com/conda/conda-build/blob/3.0.6/tests/test-recipes/metadata/_run_constrained/meta.yaml ). This will require `conda-build` 3 to accomplish.

The same should be done with `openmp` as well.

**Comment by isuruf** [comment]
@jakirkham, maybe we can have a `llvm-meta` package that all the llvm packages depend on so that the version is enforced.

**Comment by isuruf** [comment]
@jakirkham, @inducer, what do you think about my suggestion above?

**Comment by jakirkham** [comment]
I think we will be able to solve this without that once we are on `conda-build` 3.

**Comment by isuruf** [comment]
@jakirkham, `run_constrained` needs conda>=4.4, which is going to take some time for us to require users. I'd like `libcxx` and `openmp` to not be dependent on `llvmdev` or `clangdev` as they are heavy dependencies. What do you think?

**Comment by isuruf** [comment]
ping

**Pull request closed without merging**
