### PR TITLE
WIP: Add Windows (with libcxxabi)

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/libcxx-feedstock/issues/8
Replaces https://github.com/conda-forge/libcxx-feedstock/pull/10

Note: Still trying to work out issues with the `libcxxabi` build. So this is not done yet.

This is my attempt to build on Windows. Took a few tricks to get it to work right. Enumerated them below.

1. Use `clang-cl` to workaround missing [`include_next`]( https://reviews.llvm.org/D32411 ) in MSVC.
2. Various tweaks to get CMake to parse `llvm-config.exe`'s output correctly (backslashes 🙄).
3. Disable experimental libraries as they appear to be unsupported.

ref: http://libcxx.llvm.org/docs/BuildingLibcxx.html#experimental-support-for-windows

cc @isuruf

### CODE REVIEW

**Comment by jakirkham** [comment]
It looks like it is using [`MD`]( https://ci.appveyor.com/project/conda-forge/libcxx-feedstock/build/1.0.7/job/6tcxxmn9f9m8xes2#L979 ) to build, which doesn't seem right.

**Comment by jakirkham** [comment]
Also the Windows build [failure]( https://ci.appveyor.com/project/conda-forge/libcxx-feedstock/build/1.0.7/job/6tcxxmn9f9m8xes2#L1098 ) seems pretty clearly bad. Though am not finding any discussion on it.

**Comment by isuruf** [comment]
It seems like libcxxabi is not supported fully in windows. We can try to see if `libcxx` works without `libcxxabi` on windows.

**Comment by jakirkham** [comment]
Switched to build `libcxxabi` as a static library only, which works. However `libcxx` seems to run into issues during the rebuild. Am starting to wonder if Windows will require static libraries all the way through. 😞

**Comment by jakirkham** [comment]
Do we need to be building [`libunwind`]( https://github.com/llvm-mirror/libunwind ) too? Some of the linking issues are making it look like something is pretty broken with exception handling in the current Windows build.

**Comment by jakirkham** [comment]
Maybe this [SO question/answer]( https://stackoverflow.com/q/27827857 ) is relevant.

**Comment by jakirkham** [comment]
> It seems like libcxxabi is not supported fully in windows. We can try to see if `libcxx` works without `libcxxabi` on windows.

Yeah, I think you are right. May revisit this after. However, for now, have put together a fresh set of changes that builds for Windows without `libcxxabi` in PR ( https://github.com/conda-forge/libcxx-feedstock/pull/14 ).

**Comment by jakirkham** [comment]
Closing as this seems like a bad idea in light of this accepted [upstream patch]( https://reviews.llvm.org/D32320 ).

**Pull request closed without merging**
